config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
  resources :subscriptions
  resources :memberships
  resources :publishers do
    collection do
      post 'newsub'
    end
  end
    
  resources :books
  devise_for :users
  root 'library#showall'
  get 'library/mybooks'
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end
end

app/controllers/library_controller.rb
# frozen_string_literal: true

# asdadsa
class LibraryController < ApplicationController
  def showall
    @mysubs = Subscription.where(user_id: current_user.id)
    @mypubs = []
    @mysubs.each do |mysub|
      @mypubs.push(Membership.where(publisher_id: mysub.publisher_id))
    end
    @mybooks = []
    @mypubs.each do |mypub|
      mypub.each do |mp|
        @mybooks.push(Book.where(user_id: mp.user_id))
      end
    end
  end

  def mybooks
    @cur_id = current_user.id
    @mybooks = Book.where(user_id: current_user.id)
  end
end

app/helpers/library_helper.rb
module LibraryHelper
end

app/views/library/mybooks.html.erb
<h3>Мои публикации</h3>

<table class = "booklist">
<thead>
    <tr>
      <th><%="#{t('book_name')}"%></th>
      <th><%="#{t('book_genre')}"%></th>
      <th><%="#{t('book_language')}"%></th>
    </tr>
  </thead>
  <tbody style = "background-color: #e0e9fb;">
    <% @mybooks.each do |book| %>
      <tr style = "border: 2px solid rgb(24, 80, 185);", onclick="location.href = 'http://localhost:3000/books/<%= book.id %>';">
        <td><%= book.name %></td>
        <td><%= book.genre %></td>
        <td><%= book.language %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/library/showall.html.erb
<script>
    function change_background(color) {
    var subs = document.getElementById("subs");
    document.styleSheets[0].insertRule('#subs:hover {background-color: ' + color + ';}', 0);
    }
    window.addEventListener("load", function() { change_background('white') });   
</script>

<h1 align = "center" ><%=current_user.name%></h1>
<p align = "center" > <%=current_user.email%> <p>
<div class = "container", align = "center", id = "menu">
    <div class = "row">
        <div class = "col-3">
            <%= button_to 'К публикациям', books_path, method: :get, class: 'btn btn-primary' %>
        </div>
        <div class = "col-3">
            <%= button_to 'Создать публикацию', new_book_path, method: :get, class: 'btn btn-primary' %>
        </div>
        <div class = "col-3">
            <%= button_to 'Редактировать профиль', edit_user_registration_path, method: :get, class: 'btn btn-primary' %>
        </div>
        <div class = "col-3">
            <%= button_to 'Мои публикации', href = 'library/mybooks' , method: :get, class: 'btn btn-primary' %>
        </div>
    </div>
</div>
<h3> Ваши новинки </h3>
<div class = "publics">
    <% @mybooks.each do |book| %>
       <% book.each do |b| %>
        <% if b.updated_at > 3.days.ago %>
        <div class = "container", onclick="location.href = 'books/<%= b.id %>';", id = "subs">
            <div class = "row">
                <div class = "col">
                 <% @mem = Membership.where(user_id: b.user_id).first%>
                 <% @pub = Publisher.find(@mem.publisher_id) %>
                 <strong>Издательство: </strong><%= @pub.pub_house%>
                </div>
            </div>
            <div class = "row">
                <div class = "col">Название: <%= b.name %></div>
                <div class = "col">Жанр: <%= b.genre %></div>
            </div>
        </div>
        <% end %>
        <% end %>
    <% end %>
</div>