config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
  resources :subscriptions
  resources :memberships
  resources :publishers do
    collection do
      post 'newsub'
    end
  end
    
  resources :books
  devise_for :users
  root 'library#showall'
  get 'library/mybooks'
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Zachet</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <h1 class = "sitename"><strong>library</strong></h1>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%if notice%>
  <p class="notice", align = "center", style = "color: green"><%= notice %></p>
  <% end %>
  <%if alert%>
  <p class="alert", align = "center", style = "color: red"><%= alert %></p>
  <%end %>
  <% if current_user %>
  <nav class="navbar navbar-expand-lg my-primary fixed-bottom">
    <div class="container-fluid">
      <div class="collapse navbar-collapse">
        <ul class="navbar-nav">
        <%if not current_page?(root_path)%>
          <li class="nav-item active">
            <a class="nav-link" href=<%= root_path %>>Мой профиль</a>
          </li>
        <%end%>
          <li class="nav-item">
            <a class="nav-link" href=<%= books_path %>>Публикации</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href=<%= publishers_path %>>Издания</a>
          </li>
          <li class="nav-item active">
          <%= button_to "Выйти", destroy_user_session_path, method: :delete, class:"btn btn-outline-light", data: { turbo: false } %>
          </li>
        </ul>
      </div>
  </div>
</nav>
<%end%>
    <%= yield %>
  </body>
</html>